### ISSUE TITLE
interactive debugger is not starting

### ISSUE THREAD

**Issue by joka** [novareto/uvckickstart#1]
version: development
Error: running the debug shell is causing the following error:
```
$ bin/zeo start
$ bin/interactive_debugger
Traceback (most recent call last):
  File "bin/interactive_debugger", line 230, in <module>
    sys.exit(grokcore.startup.startup.interactive_debug_prompt(zope_conf="/home/joka/dev/zope/bghw/uvckickstart/project/parts/etc/zope.conf"))
  File "/home/joka/.buildout/eggs/grokcore.startup-3.0.1-py2.7.egg/grokcore/startup/startup.py", line 53, in interactive_debug_prompt
    db = zope.app.wsgi.config(zope_conf)
  File "/home/joka/.buildout/eggs/zope.app.wsgi-4.1.0-py2.7.egg/zope/app/wsgi/__init__.py", line 163, in config
    appsetup.config(options.site_definition, features=features)
  File "/home/joka/.buildout/eggs/zope.app.appsetup-4.0.0-py2.7.egg/zope/app/appsetup/appsetup.py", line 111, in config
    context = xmlconfig.file(file, context=context, execute=execute)
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 498, in file
    include(context, name, package)
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 402, in include
    processxmlfile(f, context)
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 295, in processxmlfile
    parser.parse(src)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 281, in endElementNS
    None, sys.exc_info()[2])
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/xmlconfig.py", line 272, in endElementNS
    self.context.end()
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/config.py", line 345, in end
    self.stack.pop().finish()
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/config.py", line 452, in finish
    args = toargs(context, *self.argdata)
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/config.py", line 794, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/fields.py", line 73, in fromUnicode
    value = self.context.resolve(name)
  File "/home/joka/.buildout/eggs/zope.configuration-4.1.0-py2.7.egg/zope/configuration/config.py", line 151, in resolve
    mod = __import__(mname, *_import_chickens)
  File "/home/joka/.buildout/eggs/uvcsite-2.6.0-py2.7.egg/uvcsite/__init__.py", line 14, in <module>
    from uvcsite.utils.help import HelpPage
  File "/home/joka/.buildout/eggs/uvcsite-2.6.0-py2.7.egg/uvcsite/utils/help.py", line 12, in <module>
    grok.templatedir('templates')
  File "/home/joka/.buildout/eggs/martian-1.1-py2.7.egg/martian/directive.py", line 237, in __init__
    validate(*args, **kw)
  File "/home/joka/.buildout/eggs/grokcore.view-3.0.3-py2.7.egg/grokcore/view/directive.py", line 37, in validateLocalPath
    "cannot be found." % (value, directive.name))
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/joka/dev/zope/bghw/uvckickstart/project/parts/etc/site.zcml", line 4.2-4.31
    GrokImportError: The directory 'templates' specified by the 'templatedir' directive cannot be found.
[1]    6412 exit 1     bin/interactive_debugger > debug
```
Solution: update version pinning to https://raw.githubusercontent.com/novareto/uvcsite/2.6.3/versions.cfg

**Comment by joka** [comment]
I would be happy to make a pull request to fix this and maybe other stuff in the future.
Can you allow other to make pull requests?

**Comment by goschtl** [comment]
Hey,

This is a known fact. The uvcsite 2.6.0 is a brown bag release. It should be fixed in the newest 2.6.3. I think when you update to this version it should work without any problems.

**Comment by joka** [comment]
ah ok. 
But there is still a  problem with the uvckickstart package. If I checkout and use the current master the generated buildout is using 2.6.1/versions.cfg (broken interactive-debugger) instead of ..2.6.3/versions.cfg.

By the way: I also tried other older releases of ../versions.cfg and run into other problems caused by somehow not pinned versions, like: 

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2559, in requires
    "%s has no such extra feature %r" % (self, ext)
UnknownExtra: zope.testbrowser 5.2.4 has no such extra feature 'zope-functional-testing
(this extra feature was removed in 5.0)

**Comment by goschtl** [comment]
Yes, i know about that thing. We made a mistake in using a wrong extends. We extend from a trunk versions.cfg. That file does not change in 3 years. But once it was changed it breaks a lot of our internal releases. :(

We thought about provided a fixed versions.cfg set for this old releases. But no one complained about it, until now :)

**Comment by joka** [comment]
oudated
